#!/usr/bin/env bash
# utils/leaderboard.sh — render LEADERBOARD.md, the ranked read of every rated task (GH-108).
#
# ONE SCORER, NEVER TWO. This script does NOT compute calc and does NOT apply the
# override-wins-over-calc rule. It consumes `export_timeline.py --json` and sorts on the
# `effectiveScore` the exporter already derived. A shell script re-deriving scores would be the
# exact drift class the "calc is never stored" rule exists to prevent, one layer up — the whole
# job here is sort, rank, format.
#
# LEADERBOARD.md is GENERATED and never hand-edited, following the established
# ROADMAP.md -> utils/roadmap-dashboard.sh -> ROADMAP-DASHBOARD.md pattern: committed so ranking
# changes show up in diffs and review, greppable by agents that never open a browser, readable on
# GitHub. Regeneration is idempotent — a stale checked-in copy is a review signal, not a hazard.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
DB="${LEADERBOARD_DB:-$ROOT/releases.db}"
OUT="${LEADERBOARD_OUTPUT:-$ROOT/LEADERBOARD.md}"
EXPORTER="$ROOT/utils/timeline/export_timeline.py"

usage() {
  cat <<'EOF'
Usage: bash utils/leaderboard.sh [--check] [--top N]

  Default: render LEADERBOARD.md from releases.db via export_timeline.py --json.
  --check: write nothing; exit 0 when LEADERBOARD.md is already in sync, 1 on drift.
  --top N: also print the top N to stdout (default: print nothing extra).

Env: LEADERBOARD_DB, LEADERBOARD_OUTPUT.
EOF
}

MODE="write"
TOP=0
while [ $# -gt 0 ]; do
  case "$1" in
    --check) MODE="check" ;;
    --top) TOP="${2:-5}"; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "leaderboard: unknown argument $1" >&2; usage >&2; exit 2 ;;
  esac
  shift
done

[ -f "$DB" ] || { echo "leaderboard: no releases DB at $DB" >&2; exit 2; }
[ -f "$EXPORTER" ] || { echo "leaderboard: no exporter at $EXPORTER" >&2; exit 2; }

# The payload goes through a FILE, not a pipe: `python3 - <<HEREDOC` already takes the script
# from stdin, so a piped payload would arrive on an exhausted stream.
PAYLOAD="$(mktemp "${TMPDIR:-/tmp}/leaderboard.XXXXXX.json")"
trap 'rm -f "$PAYLOAD"' EXIT
python3 "$EXPORTER" --db "$DB" --json > "$PAYLOAD"

RENDERED="$(python3 - "$PAYLOAD" "$TOP" <<'PY'
import json, sys

payload = json.load(open(sys.argv[1]))
top_n = int(sys.argv[2])

# ratedTasks is the complete, already-ranked set the exporter emits: every rated roadmap row
# once,
# annotated with where it currently sits. Ranking off the release cards alone would silently omit
# every rated task still in the queue — most of the candidates for "what goes to the front".
rows = [{
    "id": t["id"],
    "title": t["title"],
    "release": t["release"] or "—",
    "lane": t["lane"],
    "score": t["metrics"]["effectiveScore"],
    "calc": t["metrics"]["calc"],
    "override": (t.get("override") or {}).get("value"),
    "axes": (t["metrics"]["pri"], t["metrics"]["sev"],
             t["metrics"]["appeal"], t["metrics"]["effort"]),
    "issue": (t.get("links") or {}).get("issue"),
} for t in payload["ratedTasks"]]

out = []
w = out.append
gen = payload.get("telemetry", {}).get("dbGeneration")
if gen:
    w("<!-- releases-app generation: %s -->" % gen)
w("<!-- GENERATED by utils/leaderboard.sh from releases.db — do not hand-edit. -->")
w("")
w("# Leaderboard")
w("")
w("Every rated task in the ledger, highest first. **Higher is better on every axis**, effort")
w("included — it scores cheapness, not cost, so a 90/90/90/90 item reads as what it is: a")
w("screaming quick win. `calc` is the equal-weighted sum of the four axes (4–400) and is derived,")
w("never stored. `ovr` is the operator override; where it exists it replaces `calc` for ranking,")
w("while the four axes keep their honest values underneath.")
w("")
if not rows:
    w("_No rated tasks yet. Add `rated N/N/N/N` to a ROADMAP.md entry and run "
      "`releases roadmap sync`._")
else:
    w("| # | score | task | release | lane | pri | sev | appeal | effort | calc | ovr |")
    w("|--:|------:|------|---------|------|----:|----:|-------:|-------:|-----:|----:|")
    for i, r in enumerate(rows, 1):
        title = r["title"].replace("|", "\\|")
        label = "[%s](%s)" % (r["id"], r["issue"]) if r["issue"] else r["id"]
        w("| %d | **%d** | %s — %s | %s | %s | %d | %d | %d | %d | %d | %s |"
          % (i, r["score"], label, title, r["release"], r["lane"],
             r["axes"][0], r["axes"][1], r["axes"][2], r["axes"][3], r["calc"],
             str(r["override"]) if r["override"] is not None else "—"))
    w("")
    w("**Top of the line:** %s — %s (score %d%s)."
      % (rows[0]["id"], rows[0]["title"], rows[0]["score"],
         ", operator override" if rows[0]["override"] is not None else ""))
w("")
w("Source: `releases.db` via `export_timeline.py --json`. Regenerate with "
  "`bash utils/leaderboard.sh`.")

if top_n:
    for r in rows[:top_n]:
        print("%d\t%s\t%s" % (r["score"], r["id"], r["title"]), file=sys.stderr)
print("\n".join(out))
PY
)"

if [ "$MODE" = "check" ]; then
  if [ -f "$OUT" ] && [ "$RENDERED" = "$(cat "$OUT")" ]; then
    echo "leaderboard: $OUT is in sync"
    exit 0
  fi
  echo "leaderboard: $OUT is stale — run 'bash utils/leaderboard.sh'" >&2
  exit 1
fi

printf '%s\n' "$RENDERED" > "$OUT"
echo "leaderboard: wrote $OUT"
