#!/usr/bin/env bash
# utils/roadmap-dashboard.sh — render a read-only dashboard from ROADMAP.md (GH-27).

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# GH-272: releases-merge-resolve.sh drives this renderer against a --root TARGET repo —
# the ledger it renders and the dashboard it writes must follow the target, not this
# script's own checkout. Self-location stays the default for every other caller.
ROOT="${ROADMAP_DASHBOARD_ROOT:-$(cd "$HERE/.." && pwd)}"
SOURCE_FILE="${ROADMAP_DASHBOARD_SOURCE:-"$ROOT/ROADMAP.md"}"
OUTPUT_FILE="${ROADMAP_DASHBOARD_OUTPUT:-"$ROOT/ROADMAP-DASHBOARD.md"}"

usage() {
  cat <<'EOF'
Usage: bash utils/roadmap-dashboard.sh [--check]

  Default: render ROADMAP-DASHBOARD.md from the canonical root ROADMAP.md.
  --check: exit 0 when ROADMAP-DASHBOARD.md is in sync; non-zero on drift.
EOF
}

MODE="write"
if (($# > 1)); then
  usage
  exit 2
fi
if (($# == 1)); then
  case "$1" in
    --check) MODE="check" ;;
    --help|-h) usage; exit 0 ;;
    *) usage; exit 2 ;;
  esac
fi

command -v node >/dev/null 2>&1 || {
  echo "roadmap-dashboard: node is required" >&2
  exit 2
}

TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/roadmap-dashboard.XXXXXX")"
trap 'rm -rf "$TMP_DIR"' EXIT
RENDERED="$TMP_DIR/ROADMAP-DASHBOARD.md"

# GH-243: in a releases-mode repo the DB is the roadmap's source of truth and ROADMAP.md is
# frozen — render from `roadmap list --json` (each row's lossless raw_text under its section)
# instead of the legacy file. An explicit ROADMAP_DASHBOARD_SOURCE still wins (test seam), and
# any failure here falls back to the legacy file rather than emitting an empty dashboard.
if [ -z "${ROADMAP_DASHBOARD_SOURCE:-}" ] \
   && (grep -q "ROADMAP_SOURCE=releases" "$ROOT/.pdda-mode" 2>/dev/null || [ ! -f "$ROOT/ROADMAP.md" ]) \
   && [ -f "$ROOT/releases.db" ] && command -v python3 >/dev/null 2>&1; then
  DB_SRC="$TMP_DIR/roadmap-from-db.md"
  DB_JSON="$TMP_DIR/roadmap-rows.json"
  # JSON goes through a temp file passed as argv — `python3 -` takes its PROGRAM from the
  # heredoc on stdin, so piping data in as well would feed the parser nothing (the PR #240
  # rollup.sh bug, same shape). The APP resolves from HERE (this script's own checkout) while
  # --root follows $ROOT: under ROADMAP_DASHBOARD_ROOT (GH-272) the target repo may ship the
  # ledger without a utils/ tree at all.
  if python3 "$HERE/py/releases_app.py" --root "$ROOT" roadmap list --json > "$DB_JSON" 2>/dev/null \
     && python3 - "$DB_JSON" > "$DB_SRC" <<'PY'
import json, sys
with open(sys.argv[1]) as f:
    rows = json.load(f)
print("# ROADMAP (rendered from the RELEASES DB — GH-243; ROADMAP.md is frozen legacy)\n")
print("## Ledger\n")   # the renderer only counts sections below this heading
sections = {}
for r in rows:
    sections.setdefault(r.get("section") or "(unsectioned)", []).append(r)
for section, items in sections.items():
    print(f"### {section}\n")
    for r in sorted(items, key=lambda x: x.get("position") or 0):
        line = (r.get("raw_text") or "").strip()
        if not line:
            gh = f"GH-{r['gh_number']} · " if r.get("gh_number") is not None else ""
            line = f"- **{gh}{r.get('title', '')}**"
        print(line)
    print()
PY
  then
    [ -s "$DB_SRC" ] && SOURCE_FILE="$DB_SRC"
  fi
fi

if [ ! -f "$SOURCE_FILE" ]; then
  echo "roadmap-dashboard: source not found: $SOURCE_FILE" >&2
  exit 3
fi

# Resolve from HERE, not ROOT: a target ledger need not ship its own utils/ tree.
# Failure must stop rendering rather than fall back to a second, drifting vocabulary.
LEDGER_SECTIONS_JSON="$(python3 "$HERE/py/releases_app.py" roadmap sections --json)"
GEN=""
if [ -f "$ROOT/releases.db" ]; then
  GEN="$(python3 "$HERE/py/releases_app.py" --root "$ROOT" settings get generation 2>/dev/null || true)"
fi
node - "$SOURCE_FILE" "$LEDGER_SECTIONS_JSON" "$GEN" >"$RENDERED" <<'NODE'
const fs = require("fs");

const sourcePath = process.argv[2];
const raw = fs.readFileSync(sourcePath, "utf8");
const lines = raw.split(/\r?\n/);

const ledgerSections = JSON.parse(process.argv[3]);
const generation = process.argv[4] || "";
const banner = "<!-- GENERATED by utils/roadmap-dashboard.sh — DO NOT EDIT; edit the ledger through releases CLI. -->";
const knownStatuses = ["🟢", "🟡", "⏸️", "⛔", "✅", "🔮", "🔲"];
const extraStatuses = ["⚠️"];

function escapeCell(value) {
  return String(value)
    .replace(/\|/g, "\\|")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function stripMarkdown(value) {
  return value
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, "$1")
    .trim();
}

function parseBullet(block) {
  const text = block.map((line) => line.trim()).join(" ").replace(/\s+/g, " ").trim();
  const titleMatch = text.match(/^- \*\*(.+?)\*\*/);
  const title = titleMatch ? stripMarkdown(titleMatch[1]) : stripMarkdown(text.replace(/^- /, ""));

  let status = "—";
  for (const emoji of knownStatuses.concat(extraStatuses)) {
    if (text.includes(emoji)) {
      status = emoji;
      break;
    }
  }

  const links = [];
  const linkPattern = /\[([^\]]+)\]\(([^)]+)\)/g;
  let match;
  while ((match = linkPattern.exec(text)) !== null) {
    links.push(`[${match[1]}](${match[2]})`);
  }

  return { title, status, links };
}

function formatTally(items) {
  const counts = new Map();
  for (const emoji of knownStatuses) counts.set(emoji, 0);
  const extras = [];

  for (const item of items) {
    if (counts.has(item.status)) {
      counts.set(item.status, counts.get(item.status) + 1);
      continue;
    }
    if (item.status !== "—") {
      if (!counts.has(item.status)) extras.push(item.status);
      counts.set(item.status, (counts.get(item.status) || 0) + 1);
    }
  }

  const ordered = knownStatuses.slice();
  for (const emoji of extras) {
    if (!ordered.includes(emoji)) ordered.push(emoji);
  }

  return ordered.map((emoji) => `${emoji} ${counts.get(emoji) || 0}`).join(" · ");
}

const sections = new Map();
for (const heading of ledgerSections) sections.set(heading, []);

let inLedger = false;
let currentSection = null;
let unknownSection = null;
const droppedRows = [];
// GH-474: rows under a heading this renderer does not recognise. They parse fine — they are
// simply never rendered, because `sections` has no bucket for their heading. That makes them
// INVISIBLE in the view while the ledger still carries them, and invisible without a byte
// difference: the row was never in the output, so a fresh render still matches the committed
// file. `releases roadmap update/move --section` writes the section verbatim with no
// validation (utils/py/releases_app.py), so one typo is all it takes.
const unknownSectionRows = [];

for (let i = 0; i < lines.length; i++) {
  const line = lines[i];

  if (!inLedger) {
    if (/^##\s+Ledger\s*$/.test(line.trim())) inLedger = true;
    continue;
  }

  if (/^##\s+/.test(line) && !/^##\s+Ledger\s*$/.test(line.trim())) break;

  const sectionMatch = line.match(/^###\s+(.+?)\s*$/);
  if (sectionMatch) {
    const heading = sectionMatch[1].trim();
    if (sections.has(heading)) {
      currentSection = heading;
      unknownSection = null;
    } else {
      currentSection = null;
      unknownSection = heading;
    }
    continue;
  }

  if (!currentSection) {
    // GH-474: silence here used to be indistinguishable from "there was nothing to render".
    // Report the rows an unrecognised heading swallowed, so a consumer reading stderr (the
    // push guard) can tell "rendered everything" apart from "rendered everything I recognised".
    // Only list items are counted: a bullet's continuation lines ride with their bullet.
    if (unknownSection && /^\s*[-*+]\s+/.test(line)) {
      const t = line.trim();
      const m = t.match(/(?:GH-?|#)(\d+)/i);
      unknownSectionRows.push({
        section: unknownSection,
        id: m ? `#${m[1]}` : JSON.stringify(t.length > 30 ? t.slice(0, 30) + "..." : t),
        line: t,
      });
    }
    continue;
  }

  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith("<!--") || trimmed.startsWith("#")) continue;

  if (!/^- \*\*[^\r\n*]+?\*\*/.test(line)) {
    // GH-257: track non-empty dropped/unparseable line under an active ledger section
    const issueMatch = trimmed.match(/(?:GH-?|#)(\d+)/i);
    const id = issueMatch ? `#${issueMatch[1]}` : JSON.stringify(trimmed.length > 30 ? trimmed.slice(0, 30) + "..." : trimmed);
    droppedRows.push({ section: currentSection, id, line: trimmed });
    continue;
  }

  const block = [line];
  while (i + 1 < lines.length) {
    const next = lines[i + 1];
    if (/^###\s+/.test(next) || /^##\s+/.test(next) || /^\s*[-*+]\s+/.test(next)) break;
    block.push(next);
    i += 1;
  }
  sections.get(currentSection).push(parseBullet(block));
}

if (droppedRows.length > 0) {
  const ids = droppedRows.map((d) => d.id).join(", ");
  process.stderr.write(`roadmap-dashboard: warning: dropped ${droppedRows.length} unparseable row(s): ${ids}\n`);
}

// GH-474: a SECOND way to go missing, reported separately because the cause and the fix differ —
// the row is well-formed, its heading is not one this renderer renders. Both lines start with the
// same "warning: dropped " prefix on purpose: githooks/dashboard-staleness-guard.sh refuses on
// that prefix, so a new omission mode is caught by the existing guard without touching it.
if (unknownSectionRows.length > 0) {
  const ids = unknownSectionRows.map((d) => d.id).join(", ");
  const heads = [...new Set(unknownSectionRows.map((d) => d.section))].map((s) => JSON.stringify(s)).join(", ");
  process.stderr.write(
    `roadmap-dashboard: warning: dropped ${unknownSectionRows.length} row(s) under unrecognised section heading(s) ${heads}: ${ids}\n`
  );
}

const output = [];
if (generation) {
  output.push(`<!-- releases-app generation: ${generation} -->`);
}
output.push(banner);
output.push("");
output.push("# ROADMAP Dashboard");
output.push("");
output.push("Read-only derived view of the roadmap ledger (releases.db).");
output.push("");

for (const heading of ledgerSections) {
  const items = sections.get(heading) || [];
  output.push(`## ${heading}`);
  output.push("");
  output.push(`Summary: ${items.length} items | Tally: ${formatTally(items)}`);
  output.push("");
  output.push("| Item | Status | Links |");
  output.push("| --- | --- | --- |");
  for (const item of items) {
    const links = item.links.length > 0 ? item.links.join(" · ") : "—";
    output.push(`| ${escapeCell(item.title)} | ${escapeCell(item.status)} | ${links} |`);
  }
  if (items.length === 0) {
    output.push("| — | — | — |");
  }
  output.push("");
}

process.stdout.write(output.join("\n"));
NODE

if [[ "$MODE" == "check" ]]; then
  if [[ ! -f "$OUTPUT_FILE" ]]; then
    echo "roadmap-dashboard: missing artifact: $OUTPUT_FILE" >&2
    exit 1
  fi
  if cmp -s "$RENDERED" "$OUTPUT_FILE"; then
    echo "roadmap-dashboard: artifact is in sync"
    exit 0
  fi
  echo "roadmap-dashboard: artifact drift detected: $OUTPUT_FILE" >&2
  diff -u "$OUTPUT_FILE" "$RENDERED" || true
  exit 1
fi

cp "$RENDERED" "$OUTPUT_FILE"
echo "roadmap-dashboard: wrote $OUTPUT_FILE"
